### PR TITLE
Remove action mapping for ROS 1

### PR DESCRIPTION
**Pull request by jacobperron**
Removing until this feature is supported by the bridge.

@nuclearsandwich I think this should go in Crystal Patch 2.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
See https://github.com/ros2/example_interfaces/commit/069dca64e877f5a972914ae798d97f5c4ac3077e#r32202423

**Review by dirk-thomas — APPROVED** [review]

**Comment by jacobperron** [comment]
Expecting the `ros1_bridge` error to be gone:
[Build Status](https://ci.ros2.org/job/ci_packaging_linux/167/)

**Comment by nuclearsandwich** [comment]
> @nuclearsandwich I think this should go in Crystal Patch 2.

I'm assuming this addresses a specific issue which justifies it's backport? Can you please add it to https://github.com/ros2/ros2/issues/647

**Comment by jacobperron** [comment]
> I'm assuming this addresses a specific issue which justifies it's backport? Can you please add it to [ros2/ros2#647](https://github.com/ros2/ros2/issues/647)

I should have populated the description. It fixes a compiler warning in ROS 1 bridge, since the bridge does not yet support Actions. I'll add it to the description of ros2/ros2#647 and a comment once this is merged.

**Comment by nuclearsandwich** [comment]
> I'll add it to the description of [ros2/ros2#647](https://github.com/ros2/ros2/issues/647) and a comment once this is merged.

I added it to the changes in progress section so I don't forget about it. Feel free to move it once it merges.

**Pull request merged**
